version: "3.8"

services:
  server:
    image: swagatika957/server:latest
    container_name: offshore
    ports:
      - "9999:9999"

  client:
    image: swagatika957/client:latest
    container_name: ship
    ports:
      - "8080:8080"
    depends_on:
      - server

